### ISSUE TITLE
Please specify the module version.

### ISSUE THREAD

**Issue by zkn365** [advantch/django-alpine-js-tutorial#1]
I got the following error with Python3.10, Django4.1.7, and try it with different version of pydantic without success. Please specify the module version. Thanks.

=======================

Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "pydantic\validators.py", line 751, in pydantic.validators.find_validators
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\miniconda3\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\miniconda3\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\ProgramData\miniconda3\lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "C:\ProgramData\miniconda3\lib\site-packages\django\core\management\base.py", line 475, in check
    all_issues = checks.run_checks(
  File "C:\ProgramData\miniconda3\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\ProgramData\miniconda3\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\ProgramData\miniconda3\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
  File "C:\ProgramData\miniconda3\lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "C:\ProgramData\miniconda3\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\ProgramData\miniconda3\lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\ProgramData\miniconda3\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\ProgramData\miniconda3\lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\ProgramData\miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\WDAGUtilityAccount\Desktop\django-alpine-js-tutorial-main\config\urls.py", line 4, in <module>
    from .api import api
  File "C:\Users\WDAGUtilityAccount\Desktop\django-alpine-js-tutorial-main\config\api.py", line 2, in <module>
    from apps.dashboard.api import router as dashboard_router
  File "C:\Users\WDAGUtilityAccount\Desktop\django-alpine-js-tutorial-main\apps\dashboard\api.py", line 3, in <module>
    from .schema import TodoSchema
  File "C:\Users\WDAGUtilityAccount\Desktop\django-alpine-js-tutorial-main\apps\dashboard\schema.py", line 7, in <module>
    class TodoSchema(ModelSchema):
  File "C:\ProgramData\miniconda3\lib\site-packages\ninja\orm\metaclass.py", line 20, in __new__
    cls = super().__new__(mcs, name, bases, namespace)
  File "C:\ProgramData\miniconda3\lib\site-packages\ninja\schema.py", line 145, in __new__
    result = super().__new__(cls, name, bases, namespace, **kwargs)
  File "pydantic\main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic\validators.py", line 760, in find_validators
RuntimeError: error checking inheritance of typing.Optional (type: Optional)

**Comment by mgonzal49** [comment]
I am getting the same error. 

Were you able to resolve it?

**Comment by anastasiya178** [comment]
I got the same issue, haven't resolved it yet

**Comment by stuosk** [comment]
I got the same error with Python 3.11.3, Django 4.0.10 and pydantic 1.10.4 and fixed it with this patch:
[inhtype.txt](https://github.com/advantch/django-alpine-js-tutorial/files/11575807/inhtype.txt)

**Comment by lilian-pablo-tarodo** [comment]
> I got the same error with Python 3.11.3, Django 4.0.10 and pydantic 1.10.4 and fixed it with this patch: [inhtype.txt](https://github.com/advantch/django-alpine-js-tutorial/files/11575807/inhtype.txt)

This worked, thanks!
